# -*- coding: utf-8 -*-
"""Tratamento de Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19HIMM-2HWzrgykFsGAJnrH8nAmh4Cr-V

ANÁLISE EXPLORATÓRIA DOS DADOS DA TABELA CHURN
"""

import pandas as pd
import seaborn as srn

#lendo dataset
dataset = pd.read_csv("Churn.csv", sep=';')

#Os dados apresentam erros, vamos efetuar correções
dataset.head()

#Renomeando colunas
dataset.columns = ["Id","Score","Estado","Gênero","Idade","Patrimonio","Saldo",
                   "Produtos","TemCartãoCredito","Ativo","Salario","Saiu"]

#explorando dados categóricos

#Estado
#Precisa de Correções, pois os dados correspondem somente à 
#região sul então 'RP','TD' e 'SP' são erros 
agrupado = dataset.groupby(["Estado"]).size()
agrupado

#visualização gráfica estado
agrupado.plot.bar(color='gray')

#Gênero
#Precisa de Correção pois os dados estão fora de um padrão
#F, Fem e Feminino representam a mesma coisa, o mesmo para M e Masculino
agrupado = dataset.groupby(["Gênero"]).size()
agrupado

#visualização gráfica Gênero
agrupado.plot.bar(color= 'gray')

#Analisando colunas numéricas
#score
#nada anormal
dataset["Score"].describe()

#analise gráfica 
srn.boxplot(dataset["Score"]).set_title("Score")

srn.distplot(dataset["Score"]).set_title("Score")

#Idade
#Correção necessária, contém idade negativa e idade maior que 120, 
#isso não corresponde aos padrões de idade humanas
dataset["Idade"].describe()

#análise gráfica idade
srn.boxplot(dataset["Idade"]).set_title("Idade")

srn.distplot(dataset["Idade"]).set_title("Idade")

#saldo
#nada anormal
dataset["Saldo"].describe()

srn.boxplot(dataset["Saldo"]).set_title("Saldo")

srn.distplot(dataset["Saldo"]).set_title("Saldo")

#Salario
#outliers
dataset["Salario"].describe()

srn.boxplot(dataset["Salario"]).set_title("Salario")

srn.distplot(dataset["Salario"]).set_title("Salario")

#Verificando valores NaN
#8 NaN em Estado e 7 Nan em Salario
dataset.isnull().sum()

dataset.head()